/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Donation } from '../../models/donation';

export interface GetAllDonation$Params {
}

export function getAllDonation(http: HttpClient, rootUrl: string, params?: GetAllDonation$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Donation>>> {
  const rb = new RequestBuilder(rootUrl, getAllDonation.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Donation>>;
    })
  );
}

getAllDonation.PATH = '/getAllDonation';
