/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Donation } from '../../models/donation';

export interface GetDonationById$Params {
  id: number;
}

export function getDonationById(http: HttpClient, rootUrl: string, params: GetDonationById$Params, context?: HttpContext): Observable<StrictHttpResponse<Donation>> {
  const rb = new RequestBuilder(rootUrl, getDonationById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Donation>;
    })
  );
}

getDonationById.PATH = '/getDonationById{id}';
