/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Donation } from '../../models/donation';

export interface SaveDonation$Params {
      body: Donation
}

export function saveDonation(http: HttpClient, rootUrl: string, params: SaveDonation$Params, context?: HttpContext): Observable<StrictHttpResponse<Donation>> {
  const rb = new RequestBuilder(rootUrl, saveDonation.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Donation>;
    })
  );
}

saveDonation.PATH = '/saveDonation';
