spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/charity
server:
  port: 8020

jwt:
  auth:
    concerter:
      resource-id: tayeb-rest-api
      principle-attribute: preferred_username