/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  id?: string;
  isRecipientOnline?: boolean;
  lastMessageTime?: string;
  lastmessage?: string;
  name?: string;
  receicerId?: string;
  senderId?: string;
  unreadCount?: number;
}
