/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

// import { CompagneCollecte } from '../models/compagne-collecte';
export interface Commenter {
  // compagneCollecte?: CompagneCollecte;
  contenu?: string;
  dateCommentaire?: string;
  id?: number;
}
