/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompagneCollecte {
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  id?: number;
  montantCollecte?: number;
  moyenPaiement?: 'CARTE_BANCAIRE' | 'VIREMENT' | 'ESPECES' | 'PAYPAL';
  objectif?: number;
  titre?: string;
}
