/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Post {
  content?: string;
  date?: string;
  id?: number;
  img?: string;
  likeCount?: number;
  name?: string;
  postedBy?: string;
  tags?: Array<string>;
  viewCount?: number;
}
