/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  id?: number;
  image?: string;
  lastName?: string;
  password?: string;
  passwordResetToken?: string;
  phonenumber?: string;
  role?: 'ADMIN' | 'SUBSCRIBER' | 'DONATEUR' | 'ASSOCIATION' | 'USER' | 'REFUGEE' | 'SPONSOR';
  username?: string;
}
