/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Training } from '../../models/training';

export interface CreateTraining$Params {
      body: Training
}

export function createTraining(http: HttpClient, rootUrl: string, params: CreateTraining$Params, context?: HttpContext): Observable<StrictHttpResponse<Training>> {
  const rb = new RequestBuilder(rootUrl, createTraining.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Training>;
    })
  );
}

createTraining.PATH = '/trainings/add-training';
