/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { GrantedAuthority } from './models/granted-authority';
export { Opportunity } from './models/opportunity';
export { Training } from './models/training';
export { User } from './models/user';
