/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TrainingControllerService } from './services/training-controller.service';
export { UserControllerService } from './services/user-controller.service';
export { OpportunityControllerService } from './services/opportunity-controller.service';
export { DemoControllerService } from './services/demo-controller.service';
