/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompagneCollecte } from '../../models/compagne-collecte';

export interface GetAllCompagneCollecte$Params {
}

export function getAllCompagneCollecte(http: HttpClient, rootUrl: string, params?: GetAllCompagneCollecte$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CompagneCollecte>>> {
  const rb = new RequestBuilder(rootUrl, getAllCompagneCollecte.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CompagneCollecte>>;
    })
  );
}

getAllCompagneCollecte.PATH = '/getAllCompagneCollecte';
