/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompagneCollecte } from '../../models/compagne-collecte';

export interface GetCompagneCollecteById$Params {
  id: number;
}

export function getCompagneCollecteById(http: HttpClient, rootUrl: string, params: GetCompagneCollecteById$Params, context?: HttpContext): Observable<StrictHttpResponse<CompagneCollecte>> {
  const rb = new RequestBuilder(rootUrl, getCompagneCollecteById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompagneCollecte>;
    })
  );
}

getCompagneCollecteById.PATH = '/getCompagneCollecteById{id}';
