/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Commenter } from '../../models/commenter';

export interface SaveCommenter$Params {
      body: Commenter
}

export function saveCommenter(http: HttpClient, rootUrl: string, params: SaveCommenter$Params, context?: HttpContext): Observable<StrictHttpResponse<Commenter>> {
  const rb = new RequestBuilder(rootUrl, saveCommenter.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Commenter>;
    })
  );
}

saveCommenter.PATH = '/saveCommenter';
