/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { hello } from '../fn/demo-controller/hello';
import { Hello$Params } from '../fn/demo-controller/hello';
import { hello2 } from '../fn/demo-controller/hello-2';
import { Hello2$Params } from '../fn/demo-controller/hello-2';

@Injectable({ providedIn: 'root' })
export class DemoControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `hello()` */
  static readonly HelloPath = '/api/v1/demo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hello()` instead.
   *
   * This method doesn't expect any request body.
   */
  hello$Response(params?: Hello$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return hello(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hello$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hello(params?: Hello$Params, context?: HttpContext): Observable<string> {
    return this.hello$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `hello2()` */
  static readonly Hello2Path = '/api/v1/demo/hello-2';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hello2()` instead.
   *
   * This method doesn't expect any request body.
   */
  hello2$Response(params?: Hello2$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return hello2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hello2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hello2(params?: Hello2$Params, context?: HttpContext): Observable<string> {
    return this.hello2$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
